version: '3.8'

services:
  database:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: boot
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
      - ./certs:/etc/mysql/certs

    command:
      - --require_secure_transport=ON
      - --ssl-ca=/etc/mysql/certs/ca.crt
      - --ssl-cert=/etc/mysql/certs/mysql.crt
      - --ssl-key=/etc/mysql/certs/mysql.key
      - --bind-address=0.0.0.0 
    ports:
      - "3307:3306" # Corrected port mapping for MySQL

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot || exit 1"]
      interval: 10s
      retries: 10
    networks:
      - backend

  cert-gen:
    image: alpine
    volumes:
      - ./certs:/certs
    entrypoint:
      - /bin/sh
      - -c
      - |
        apk add --no-cache openssl &&
        openssl genpkey -algorithm RSA -out /certs/mysql.key -pkeyopt rsa_keygen_bits:2048 &&
        openssl req -new -key /certs/mysql.key -out /certs/mysql.csr -subj "/CN=mysql/O=myorg/C=US" &&
        openssl x509 -req -in /certs/mysql.csr -signkey /certs/mysql.key -out /certs/mysql.crt -days 365 &&
        openssl genpkey -algorithm RSA -out /certs/ca.key -pkeyopt rsa_keygen_bits:2048 &&
        openssl req -new -x509 -key /certs/ca.key -out /certs/ca.crt -days 1095 -subj "/CN=Certificate Authority/O=myorg/C=US" &&
        chmod 600 /certs/* && chown 999:999 /certs/*
    restart: "no"

  backend:
    build:
      context: ../Server-API-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: database
      MYSQL_DBNAME: server_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: boot
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
      - frontend

  frontend:
    build:
      context: ../Server-UI-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend


volumes:
  mysql_data:

networks:
  frontend:
  backend: